import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#171f33",
        "secondary": "#ffed76",
        "secondary-fixed": "#fce425",
        "on-error-container": "#ffdad6",
        "on-primary": "#003354",
        "on-secondary-container": "#635800",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#504700",
        "tertiary-fixed": "#d3e4fe",
        "on-primary-fixed": "#001d33",
        "surface-variant": "#2d3449",
        "on-primary-container": "#5994cb",
        "primary-container": "#002b48",
        "on-tertiary-container": "#8191a9",
        "surface-tint": "#98cbff",
        "background": "#0b1326",
        "on-surface-variant": "#c5c6cd",
        "inverse-on-surface": "#283044",
        "primary": "#98cbff",
        "secondary-fixed-dim": "#dec800",
        "surface-bright": "#31394d",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#201c00",
        "surface-dim": "#0b1326",
        "on-secondary": "#373100",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-container-highest": "#2d3449",
        "surface-container-low": "#131b2e",
        "on-tertiary": "#213145",
        "outline-variant": "#45474c",
        "inverse-surface": "#dae2fd",
        "inverse-primary": "#1d6296",
        "primary-fixed": "#cfe5ff",
        "on-primary-fixed-variant": "#004a77",
        "secondary-container": "#e7d000",
        "tertiary-container": "#1a2a3e",
        "surface-container-lowest": "#060e20",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#0b1c30",
        "tertiary": "#b7c8e1",
        "on-tertiary-fixed-variant": "#38485d",
        "primary-fixed-dim": "#98cbff",
        "surface-container-high": "#222a3d",
        "surface": "#0b1326",
        "outline": "#8f9097",
      },
      fontFamily: {
        headline: ["var(--font-headline)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "system-ui", "sans-serif"],
        label: ["var(--font-body)", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
